#!/usr/bin/env node
// Build MODULES.md from every MODULE.md (frontmatter: name, purpose, interface, errors, tests, depends-on).
//   node scripts/modules-map.mjs          # write MODULES.md
//   node scripts/modules-map.mjs --check  # exit 1 if MODULES.md is stale
import { readFileSync, writeFileSync, existsSync } from "node:fs"
import { globSync } from "node:fs"

const files = globSync(["modules/*/MODULE.md", "testing/MODULE.md", "review/MODULE.md"]).sort()
const rows = files.map((file) => {
  const text = readFileSync(file, "utf8")
  const fm = /^---\n([\s\S]*?)\n---/.exec(text)
  if (!fm) throw new Error(`${file}: missing frontmatter`)
  const meta = Object.fromEntries(fm[1].split("\n").filter((l) => l.includes(":")).map((l) => {
    const i = l.indexOf(":"); return [l.slice(0, i).trim(), l.slice(i + 1).trim()]
  }))
  for (const k of ["name", "purpose", "interface", "errors", "tests"]) if (!meta[k]) throw new Error(`${file}: missing ${k}`)
  const deps = (meta["depends-on"] ?? "[]").replace(/^\[|\]$/g, "").split(",").map((s) => s.trim()).filter(Boolean)
  return { ...meta, deps, file, interfaceExists: existsSync(meta.interface) }
})
const lines = ["# Modules", "", "Generated by `npm run map` from every `MODULE.md` — do not edit. Read this first; open a module's `MODULE.md` for the detail.", "",
  "| Module | Purpose | Interface | Depends on |", "| --- | --- | --- | --- |",
  ...rows.map((r) => `| [\`${r.name}\`](${r.file}) | ${r.purpose} | \`${r.interface}\`${r.interfaceExists ? "" : " *(missing)*"} | ${r.deps.map((d) => `\`${d}\``).join(", ") || "—"} |`),
  "", `${rows.length} module(s).`, ""]
const out = lines.join("\n")
if (process.argv.includes("--check")) {
  const current = existsSync("MODULES.md") ? readFileSync("MODULES.md", "utf8") : ""
  if (current !== out) { console.error("MODULES.md is stale — run `npm run map`"); process.exit(1) }
  console.log("MODULES.md is current")
} else {
  writeFileSync("MODULES.md", out); console.log(`wrote MODULES.md (${rows.length} modules)`)
}
