#!/usr/bin/env node
// Vendored source stays aligned with the dependency pin. Reads repos/vendored.json (written by the
// vendor-source skill) and fails when a pinned package's version in package.json differs from the
// vendored ref, or when repos/VENDORED.md no longer matches the manifest. Silent where nothing is
// vendored or an entry carries no pin.
//   node scripts/vendored-check.mjs   # exit 1 on drift; `npm run check` runs it
import { existsSync, readFileSync } from "node:fs"

const MANIFEST = "repos/vendored.json"
const MAP = "repos/VENDORED.md"

// Keep in step with renderVendoredMd in the vendor-source skill (scripts/vendor-source.mjs).
function renderVendoredMd(manifest) {
  const rows = manifest.repos.map((r) => `| \`${r.name}\` | ${r.url} | \`${r.ref}\` | \`${r.commit.slice(0, 7)}\` | ${r.size_mb} MB | ${r.vendored_at.slice(0, 10)} | ${r.pins ? `\`${r.pins.package}\` in \`${r.pins.from}\`` : "—"} |`)
  return ["# Vendored source", "",
    "Generated by `vendor-source` from `repos/vendored.json` — do not edit. Everything under `repos/` is read-only reference: read it to see how a library really works, never edit it, never import from it (the seam lint fails), never treat it as work in scope. `vendor-source update` refreshes it.", "",
    "| Name | Source | Ref | Commit | Size | Vendored | Pinned by |", "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows, "", `${manifest.repos.length} vendored repo(s).`, ""].join("\n")
}

if (!existsSync(MANIFEST)) {
  console.log("nothing vendored")
  process.exit(0)
}
const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"))
const problems = []
const versions = {}
for (const entry of manifest.repos) {
  if (!entry.pins) continue
  const { package: pkg, from } = entry.pins
  if (!(from in versions)) {
    const p = existsSync(from) ? JSON.parse(readFileSync(from, "utf8")) : {}
    versions[from] = { ...(p.devDependencies ?? {}), ...(p.dependencies ?? {}) }
  }
  const version = versions[from][pkg]
  const expected = `${pkg}@${version}`
  if (!version) problems.push(`${entry.name}: ${from} no longer lists ${pkg}, but ${entry.prefix} is vendored at ${entry.ref} — run \`vendor-source remove ${entry.name}\` or restore the dependency`)
  else if (entry.ref !== expected) problems.push(`${entry.name}: ${from} pins ${pkg} ${version} but ${entry.prefix} is vendored at ${entry.ref} — run \`vendor-source update ${entry.name}\` (or change the pin back)`)
}
if (!existsSync(MAP) || readFileSync(MAP, "utf8") !== renderVendoredMd(manifest)) {
  problems.push(`${MAP} does not match ${MANIFEST} — it is generated; restore it from git or run a vendor-source verb`)
}
if (problems.length) {
  console.error("vendored source is out of step with the repo:\n" + problems.map((p) => `  - ${p}`).join("\n"))
  process.exit(1)
}
console.log(`vendored source is current (${manifest.repos.length} repo(s))`)
